version: "3.9"
services:
  db:
    image: postgres:13
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./backend/infra/database/init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      POSTGRES_DB: oh-my-fi
      POSTGRES_USER: db_user
      POSTGRES_PASSWORD: ilovemyfi
    ports:
      - "5432:5432"
    
volumes:
  db_data:
